sudo: false
os:
  - linux

language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libfuse-dev

cache:
  directories:
    - $HOME/.cargo

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo build

notifications:
  email:
    on_success: never
